FROM node:18 AS build
WORKDIR /app
COPY frontend/incident-management/package*.json ./
RUN npm cache clean --force && npm install --verbose
COPY frontend/incident-management .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
