FROM maven:3.8.1-openjdk-17-slim as build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY backend .
RUN mvn package

FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /app/target/incident-management-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java", "-jar", "incident-management-0.0.1-SNAPSHOT.jar"]